{
 "title": "BTC Rate <-> Balance",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Symbol",
    "query": {
     "query": "label_values(trader_trendline_1, symbol)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "BTC Balance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "trader_btc_balance > 0.015 != 0"
    }
   ]
  },
  {
   "title": "BTC Change",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(trader_btc_change[5m]) < 500 > -500",
     "legendFormat": "Average (grafana)"
    },
    {
     "expr": "avg_over_time(trader_btc_change[1m]) < 500 > -500",
     "legendFormat": "Average (grafana)"
    }
   ]
  },
  {
   "title": "Symbol Close",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "trader_klines_close_price{job=\"binance-cody\", symbol=~\"$Symbol\"} != 0"
    }
   ]
  },
  {
   "title": "BTC/USD Value",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "trader_btc_rate != 0" }
   ]
  },
  {
   "title": "Rally Parties",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(trader_rally_parties[15s])"
    }
   ]
  }
 ]
}