{
 "title": "Balances",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "BTC Balance",
   "type": "graph",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "trader_btc_balance < 0.018 > 0.0155"
    }
   ]
  },
  {
   "title": "Positions",
   "type": "table",
   "gridPos": { "h": 17, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((trader_klines_close_price > trader_klines_open_price or trader_klines_open_price) - trader_position_buy_rate) / trader_position_buy_rate * 100"
    }
   ]
  },
  {
   "title": "Balance",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(trader_btc_balance != 0) * trader_btc_rate != 0"
    },
    { "expr": "trader_btc_balance != 0" },
    { "expr": "trader_btc_rate != 0" }
   ]
  },
  {
   "title": "Lifetime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(trader_btc_balance != 0) - 0.0240551",
     "legendFormat": "Balance"
    }
   ]
  },
  {
   "title": "24 Hour",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((avg_over_time(trader_btc_balance[1h]) != 0) - (avg_over_time(trader_btc_balance[1h] offset 24h) != 0)) / (avg_over_time(trader_btc_balance[1h]) != 0) * 100"
    }
   ]
  },
  {
   "title": "6 Hour",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((avg_over_time(trader_btc_balance[1h]) < 0.02 > 0.01595) - (avg_over_time(trader_btc_balance[1h] offset 6h) < 0.02 > 0.01595)) / (avg_over_time(trader_btc_balance[1h]) < 0.02 > 0.01595) * 100"
    }
   ]
  },
  {
   "title": "1 Hour",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((avg_over_time(trader_btc_balance[1h])  != 0 < 0.02 > 0.01595) - (avg_over_time(trader_btc_balance[1h] offset 1h)  != 0 < 0.02 > 0.01595)) / (avg_over_time(trader_btc_balance[1h]) != 0 < 0.02 > 0.01595) * 100"
    }
   ]
  },
  {
   "title": "Fuel",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trader_balance{symbol=\"BNB\"} != 0"
    }
   ]
  },
  { "title": "Symbols", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Enter Eligible",
   "type": "table",
   "gridPos": { "h": 23, "w": 10, "x": 0, "y": 19 },
   "targets": [
    { "expr": "trader_trendline_1" },
    { "expr": "trader_trendline_3", "legendFormat": "3 Hour" },
    { "expr": "trader_trendline_6", "legendFormat": "6 Hour" }
   ]
  }
 ]
}