{
 "title": "Position",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Symbol",
    "query": {
     "query": "label_values(trader_trendline_1, symbol)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Close Price",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "trader_klines_close_price{job=\"binance-cody\", symbol=~\"$Symbol\"} != 0",
     "legendFormat": "Close"
    },
    {
     "expr": "trader_enter_threshold{job=\"binance-cody\", symbol=~\"$Symbol\"} != 0",
     "legendFormat": "Enter"
    },
    {
     "expr": "trader_position_buy_rate{job=\"binance-cody\", symbol=~\"$Symbol\"} != 0",
     "legendFormat": "Buy Rate"
    },
    {
     "expr": "trader_trailing_stoploss_threshold{job=\"binance-cody\", symbol=~\"$Symbol\"} != 0",
     "legendFormat": "Trailing Stoploss Threshold"
    }
   ]
  },
  {
   "title": "Buy Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "trader_position_buy_rate{symbol=\"$Symbol\"}"
    }
   ]
  },
  {
   "title": "Profit",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "((trader_klines_close_price{symbol=\"$Symbol\"} < trader_klines_open_price{symbol=\"$Symbol\"} or trader_klines_open_price{symbol=\"$Symbol\"}) - trader_position_buy_rate{symbol=\"$Symbol\"}) / trader_position_buy_rate{symbol=\"$Symbol\"} * 100"
    }
   ]
  },
  {
   "title": "Signals",
   "type": "graph",
   "gridPos": { "h": 3, "w": 19, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(trader_buy_signal{symbol=\"$Symbol\"}[30s])",
     "legendFormat": "Buy"
    },
    {
     "expr": "rate(trader_sell_signal{symbol=\"$Symbol\"}[30s])",
     "legendFormat": "Sell"
    },
    {
     "expr": "rate(trader_trailing_stoploss_signal{symbol=\"$Symbol\"}[30s])",
     "legendFormat": "Trailing Stoploss"
    },
    {
     "expr": "rate(trader_dca_signal{symbol=\"$Symbol\"}[30s])",
     "legendFormat": "DCA"
    },
    {
     "expr": "rate(trader_take_profit_signal{symbol=\"$Symbol\"}[30s])",
     "legendFormat": "Take Profit"
    }
   ]
  },
  {
   "title": "Buy Rate",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trader_klines_close_price{symbol=\"$Symbol\"}",
     "legendFormat": "Close"
    },
    {
     "expr": "trader_klines_open_price{symbol=\"$Symbol\"}",
     "legendFormat": "Open"
    },
    {
     "expr": "trader_klines_high_price{symbol=\"$Symbol\"}",
     "legendFormat": "High"
    },
    {
     "expr": "trader_klines_low_price{symbol=\"$Symbol\"}",
     "legendFormat": "Low"
    },
    {
     "expr": "trader_trailing_stoploss_threshold{symbol=\"$Symbol\"}",
     "legendFormat": "Stop loss"
    }
   ]
  },
  {
   "title": "Orders",
   "type": "graph",
   "gridPos": { "h": 3, "w": 19, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(trader_buy_orders{symbol=\"$Symbol\"}[30s])",
     "legendFormat": "Buy"
    },
    {
     "expr": "rate(trader_sell_orders{symbol=\"$Symbol\"}[30s])",
     "legendFormat": "Sell"
    },
    {
     "expr": "rate(trader_cancel_orders{symbol=\"$Symbol\"}[30s])",
     "legendFormat": "Cancel"
    }
   ]
  },
  {
   "title": "Balance",
   "type": "graph",
   "gridPos": { "h": 3, "w": 19, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "trader_balance{symbol=~\"$Symbol\"} != 0"
    }
   ]
  }
 ]
}